# Generated by Django 4.2.5 on 2024-12-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_department', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('stage', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('educations', models.TextField(blank=True, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('disqualified_at', models.DateTimeField(blank=True, null=True)),
                ('disqualification_category', models.CharField(blank=True, max_length=255, null=True)),
                ('disqualification_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('disqualification_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='scoring.candidate')),
            ],
        ),
    ]
