# Generated by Django 4.2.5 on 2024-12-02 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created.', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Set to False when an element is deleted'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at'),
        ),
    ]
