# Generated by Django 4.2.5 on 2024-12-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_scoringtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
    ]
