# Generated by Django 4.2.5 on 2024-12-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_candidate_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience_years',
        ),
    ]
